update: 파일 확장자 변경

diff --git a/.github/workflows/pr-build-and-test.yml b/.github/workflows/pr-build-and-test.yml
--- a/.github/workflows/pr-build-and-test.yml
+++ b/.github/workflows/pr-build-and-test.yml
@@ -18,7 +18,7 @@ jobs:
         with:
           fetch-depth: 0
       - name: Verify docker-compose.test.yml exists
-        run: ls -la && test -f docker-compose.test.yaml || (echo "docker-compose.test.yml not found" && exit 1)
+        run: ls -la && test -f docker-compose.test.yaml || (echo "docker-compose.test.yaml not found" && exit 1)
       - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
@@ -35,10 +35,10 @@ jobs:
       - name: Set up Docker Compose
         uses: docker/setup-compose-action@v1
         with:
-          compose-version: '2.29.2' # 2025년 5월 기준 최신 버전
+          compose-version: '2.29.2'
       - name: Build and run Docker Compose
         run: |
-          docker compose -f docker-compose.test.yml up -d
+          docker compose -f docker-compose.test.yaml up -d
           sleep 120
           for i in {1..30}; do
             if curl -s http://localhost:8080/api/v2/health/check | grep -q '"OK"'; then
@@ -54,4 +54,4 @@ jobs:
         run: ./gradlew clean integrationTest --info
       - name: Stop Docker Compose
         if: always()
-        run: docker compose -f docker-compose.test.yml down
+        run: docker compose -f docker-compose.test.yaml down
