update: 파일 확장자 변경

diff --git a/.github/workflows/pr-build-and-test.yml b/.github/workflows/pr-build-and-test.yml
--- a/.github/workflows/pr-build-and-test.yml
+++ b/.github/workflows/pr-build-and-test.yml
@@ -18,7 +18,7 @@ jobs:
         with:
           fetch-depth: 0
       - name: Verify docker-compose.test.yml exists
-        run: ls -la && test -f docker-compose.test.yml || (echo "docker-compose.test.yml not found" && exit 1)
+        run: ls -la && test -f docker-compose.test.yaml || (echo "docker-compose.test.yml not found" && exit 1)
       - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
